services:
  web:
    build: 
      context: ./patent-infringement-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./patent-infringement-service:/app
      - /patent-infringement-service/app/__pycache__
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-patent
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  frontend:
    build: 
      context: ./patent-infringement-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - VITE_SERVICE_HOST=${SERVICE_HOST}:8000

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge