services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=my-redis-password
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-patent
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=my-redis-password
    networks:
      - app-network
    # command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge